//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbandoORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public string numero { get; set; }
        public string tipo { get; set; }
        public int contacto_id { get; set; }
        public string nombre_agenda { get; set; }
    
        public virtual Contacto Contacto { get; set; }
    }
}
